module.exports = {
  MESSAGE_PAGE_DEFAULT: 40,
  MESSAGE_PAGE_MAX: 100,
  SEARCH_MESSAGES_LIMIT: 50,
  GLOBAL_SEARCH_LIMIT: 50,
  DIRECTORY_SEARCH_LIMIT: 5,
  UPLOAD_MAX_BYTES: 50 * 1024 * 1024,
  SCHEDULED_JOB_MS: 5000,
  TYPING_DEBOUNCE_MS: 300,
  SOCKET_RATE_WINDOW_MS: 1000,
  SOCKET_MESSAGE_MAX_PER_WINDOW: 30,
  LINK_PREVIEW_TIMEOUT_MS: 3000,
  LINK_PREVIEW_MAX_BYTES: 512 * 1024,
  LINK_PREVIEW_USER_AGENT: 'HushBot/1.0',
  AVATAR_DATA_URL_MAX_BYTES: 280 * 1024,
  UPLOAD_DISABLED_HTTP: 410,
  UPLOAD_DISABLED_MSG: 'Загрузка на сервер отключена. Медиа передаётся E2E между устройствами.',
  CHANNEL_ROLES: ['owner', 'admin', 'moderator', 'member'],
  CHANNEL_ADMIN_ROLES: ['owner', 'admin', 'moderator'],
  PIN_ROLES: ['owner', 'admin', 'moderator'],
  DEFAULT_STUN_SERVERS: [
    { urls: 'stun:stun.l.google.com:19302' },
    { urls: 'stun:stun1.l.google.com:19302' },
  ],
  MEDIA_LOCAL_PREFIX: 'local://',
};
